IMDB:
    # Authentication method to be used for IMDb
    # The value must be one of the following:
    #   credentials - dependent fields [IMDB_EMAIL] [IMDB_PASSWORD]
    #   cookies     - dependent fields [IMDB_COOKIEATMAIN] [IMDB_COOKIEUBIDMAIN]
    #   none        - no dependent fields
    AUTH: credentials
    # IMDb account email address
    EMAIL: robert.sinn1992@googlemail.com
    # IMDb account password
    PASSWORD: Popolino1102
    # The cookies can be used as a fallback if captcha is preventing the authentication flow
    # Log into your IMDb account from a web browser, inspect the cookies and retrieve the value of cookie:
    # name: at-main | domain: .imdb.com
    COOKIEATMAIN: Atza|IwEBIHjQLXeIYMlw2sRhFChNKPpYefWEIlFzlFQKf9tcuuwXA1U_2LpmUbAwnhIc1MEHHV5nfKlthoDlJCBtDWxADrXXEn_LNEZHF-SKRDr1KJL7b1nAzWd9d37GwD1fvLzLnsuBjkS2Ce0HHBwQbkXOfLgaF72KMSEahozKAW_agxHDTBj_Azku4BrKC0NipFdzNq0qDkifJNOpk5nQc-eaTLzsYMJCFr9x7CQrkYVUYU5Pxg
    # The cookies can be used as a fallback if captcha is preventing the authentication flow
    # Log into your IMDb account from a web browser, inspect the cookies and retrieve the value of cookie:
    # name: ubid-main | domain: .imdb.com
    COOKIEUBIDMAIN: 
    # Array of IMDb lists that you would like synced to Trakt
    # If this array is empty, all IMDb lists will be synced to Trakt
    # Keep in mind the maximum number of lists you can have in Trakt: https://twitter.com/trakt/status/1536751362943332352
    # In order to get the ID of an IMDb list, open it from a browser - the ID is in the URL with format ls#########
    LISTS:
        - ls524465456
        - ls548103259
        - ls548105658
        - ls548105351
        - ls548105957
        - ls548105368
        - ls548103295
        - ls548724699
        - ls548103644
    # Print tracing logs related to browser activities
    # Can be useful for debugging purposes
    TRACE: false
    # Whether to run the browser in headless mode or not
    # For local debugging you can set this value to false
    # If running via GitHub Actions or other CI the value will always be true
    HEADLESS: true
SYNC:
    # Sync mode to be used when running the application
    # The value must be one of the following:
    #   full     - add Trakt items that do not exist, delete Trakt items that do not exist on IMDb, update Trakt items by treating IMDb as the source of truth
    #   add-only - add Trakt items that do not exist, but do not delete anything
    #   dry-run  - identify what Trakt items would be added / deleted / updated
    MODE: dry-run
    # Whether to sync history or not. If set to true, history will be synced
    # When IMDB_AUTH is none, history will be ignored
    HISTORY: true
    # Whether to sync ratings or not. If set to true, ratings will be synced
    # When IMDB_AUTH is none, ratings will be ignored
    RATINGS: true
    # Whether to watchlist or not. If set to true, watchlist will be synced
    # When IMDB_AUTH is none, watchlist will be ignored
    WATCHLIST: true
    # Maximum duration to run the syncer
    # Users with large IMDb/Trakt libraries might have to increase the timeout value accordingly
    # Valid time units are: ns, us (or µs), ms, s, m, h
    TIMEOUT: 10m
TRAKT:
    # Trakt app client ID
    # You need to replace this value with your own, the default value is for illustrative purposes only
    CLIENTID: 8cf937fa44637d73a707732b06bb7eacd00c169cd46069888de762574c2e81ba
    # Trakt app client secret
    # You need to replace this value with your own, the default value is for illustrative purposes only
    CLIENTSECRET: 1591094fbf962c37eddd4ceb9957236915620510b3892257d4a61aeb7a23aaed
    # Trakt account email address (not to be confused with username)
    # You need to replace this value with your own, the default value is for illustrative purposes only
    EMAIL: robsem92@gmail.com
    # Trakt account password
    # You need to replace this value with your own, the default value is for illustrative purposes only
    PASSWORD: Popolino1102!
